---
format:
  pdf:
    toc: true
    cite-method: biblatex
    biblio-style: nature
    mainfont: EB Garamond
    sansfont: Libertinus Sans
    fontsize: 10pt
    geometry:
      - margin=20mm
      - paperwidth=17cm
      - paperheight=24cm
    colorlinks: true
    linkcolor: DarkSlateBlue
    urlcolor: DarkRed
    citecolor: DarkSlateBlue
    link-citations: true
    number-sections: false
    pdf-engine: lualatex
    # csl: nature.csl
    keep-tex: true
# biblio-title: "References"
bibliography: refs.bib
editor: visual
---

\newpage

# Preface

The journey of my PhD has been a fulfilling expedition, layered with explorations, discoveries, struggles, and growth. This endeavor was fueled by my interest in understanding the objective measurements of physical behavior and sleep. During my Masters, I found myself increasingly engrossed in these domains.

My subsequent role as a research assistant at Aarhus University opened another dimension of learning for me. The works of my peers, employing machine learning and advanced statistics on accelerometer data, intrigued me. It was as if I found the nexus of my research interests, a perfect alignment that seamlessly fused my curiosities and passions.

One of the most significant hurdles was my limited experience with programming and machine learning, which proved to be a steep learning curve. However, through persistence, I slowly developed the necessary skills to analyze and interpret my data effectively. Another major setback was the failed data collection for my third paper. I spent months visiting families, mounting an ambulatory PSG device on children before bedtime, and facing the harsh reality of dealing with poor data quality.

This thesis brings together my explorations and findings across three papers that carry a consistent emphasis on improving and validating methods to leverage accelerometer data for studying human behaviors. The common thread across these papers is the application of innovative methods, particularly machine learning techniques, to enhance the utility, reliability, and accuracy of free-living accelerometer data for monitoring human sleep and physical activity. The work presented here constitutes a substantial contribution to the field of sleep and physical activity research, particularly in the context of large-scale studies.

Two of these papers have already found their place in peer-reviewed scientific journals, and the third is under review. All of these works are included as appendices to this thesis, and their content has been weaved into the fabric of this thesis.

As I look back at my journey through the PhD program, I am grateful for this opportunity to delve deep into a subject that I am passionate about and to contribute to a field that is evolving rapidly. This experience has instilled in me a sense of tenacity and patience, qualities that I have come to value deeply. I learned that even the most frustrating problems have solutions, and the path to those solutions often leads to personal growth and novel insights.

As I stand on the precipice of my future, I am filled with a sense of anticipation and excitement for the possibilities that lie ahead. I am eager to explore new horizons, to encounter new challenges, and to continue growing as a researcher and as an individual. However, wherever I go and whatever I do, I will carry with me the memories, experiences, and lessons from this incredible journey.

These years have shaped me in ways I could never have imagined at the outset, and for that, I am profoundly grateful. As I close this chapter of my life, I do so with a sense of accomplishment and a promise of continued exploration and discovery in my field. After all, every ending is but a new beginning, and I look forward to the adventures that await.

\newpage

# Acknowledgements

Throughout this journey, there have been several people who have influenced, inspired, and supported me. My Main Supervisor, Jan Christian Brønd, deserves special mention for his guidance and patience. His commitment to nurturing my development as a researcher and lecturer has been instrumental. Our collaborative dialogues, be it at the office or during examinations, have been pivotal in my growth. I also extend my sincere gratitude to my co-supervisors \[insert name 2\] and \[insert name 3\], and my colleague \[insert name 4\], who have always provided invaluable insights and perspectives.

Amidst all the academic pursuits, my family remained the cornerstone of my journey. My wife, the bedrock of our family, kept our home running smoothly and offered endless support and curiosity about my work. The joy and love from my four children were my constant sources of motivation and inspiration.

The PhD journey has taught me the importance of rigour and attention to detail. My approach to work has been permanently shaped by my experience as a researcher. The discipline and precision that is required in research has translated into my everyday life, impacting my approach to problem-solving, decision-making, and even communication. It's impressive how research is not merely a vocation but a lens through which we view the world.

There were also moments of immense joy and satisfaction, like finally solving a complex analytical problem, having my work accepted for publication, or simply receiving positive feedback from a student or a colleague. Those moments fueled my motivation and reminded me of the importance and impact of my work.

One of the most rewarding aspects of this journey was the opportunity to be part of an international recognized and experienced research group. This gave me the chance to work with and learn from some of the most talented people in my field, to discuss ideas and collaborate on projects, and to be part of a collective effort to advance knowledge and understanding in our field.

In retrospect, this PhD journey has been much more than a professional pursuit. It has been a personal voyage of self-discovery and growth. Through the highs and lows, the victories and setbacks, the late nights and early mornings, I've discovered a resilience in myself that I hadn't known before. I found that I could rise to challenges, learn from failures, and continue to strive for excellence, no matter the odds.

In closing, I wish to express my deep gratitude for all those who have supported me throughout this journey - my supervisors, colleagues, friends, and family. Their faith in my abilities and their constant encouragement have been my pillars of strength. I hope that the work presented in this thesis reflects the depth of my dedication and the extent of my learning journey.

\newpage

# Supervisor

Associate Professor Jan Christian Brønd, PhD

Research Unit for Exercise Epedimiology, Centre of Research in Childhood Health, Department of Sports Science and Clinical Biomechanics, University of Southern Denmark, 5230 Odense, Denmark

# Assessment Committee

## Chair

Associate Professor Anders And, PhD

## Opponents

Professor Andersine And, PhD

Research Unit for Exercise Epedimiology, Centre of Research in Childhood Health, Department of Sports Science and Clinical Biomechanics, University of Southern Denmark, 5230 Odense, Denmark

Associate Professor Fætter Højben, PhD

Research Unit for Exercise Epedimiology, Centre of Research in Childhood Health, Department of Sports Science and Clinical Biomechanics, University of Southern Denmark, 5230 Odense, Denmark

# Funding

The research presented in this thesis was generously funded by TrygFonden, under grant numbers ID 130081 and 115606, and by the European Research Council, under grant number 716657. Additional support was provided by a one-year scholarship from the Faculty of Health Sciences.

\newpage

# Included Papers

## Paper I

> Manual Annotation of Time in Bed Using Free-Living Recordings of Accelerometry Data[@skovgaard_manual_2021]

published in [Sensors](https://doi.org/10.3390/s21248442).

The first paper is focused on evaluating the manual annotation to enrich datasets for use in machine learning of in-bed periods by comparing the manual annotation method with established EEG-based sleep monitoring devices and self-reported sleep diaries.

## Paper II

> Generalizability and Performance of Methods to Detect Non‑Wear with Free‑Living Accelerometer Recordings[@skovgaard_generalizability_2023]

published in [Scientific Reports](https://doi.org/10.1038/s41598-023-29666-x).

The second paper delve into a more specific challenge in physical activity sensor usage - the detection of non-wear. We propose decision tree models that combine raw acceleration and skin temperature data to detect non-wear time and emphasize the importance of external validation in machine-learned models.

## Paper III

> Improving Sleep Quality Estimation: A Comparative Study of Machine Learning and Deep Learning Techniques Utilizing Free-Living Accelerometer Data from Thigh-Worn Devices and EEG-Based Sleep Tracking

Submitted to [npj Digital Medicin](https://www.nature.com/npjdigitalmed/).

The third paper focuses on sleep quality estimation using machine learning and deep learning models. We evaluate these models using data from thigh-worn accelerometers, presenting a potential alternative for large-scale sleep studies. We underscore the challenges of classifying awake periods during in-bed time and the need for further precision in assessing sleep quality metrics an individual-basis.

\newpage

# English Summary

bla

\newpage

# Danish Summary

bla

\newpage

# Introduction

## Outline of Introduction Section

### Overview and Background

-   The importance of sleep and physical activity tracking in health research.
-   The limitations of traditional methods, such as polysomnography and self-reported diaries.
-   The emergence and potential of wearable accelerometers and machine learning models in this field.

Throughout the course of a single day, a variety of activities encompass physical behaviors including sleep, physical activity (PA), and sedentary behavior[@rolloWholeDayMatters2020]. Over the last decade, numerous studies have highlighted the unique health advantages of high PA levels, especially moderate-to-vigorous physical activity (MVPA)[@krausPhysicalActivityAllCause2019; @leeEffectPhysicalInactivity2012], minimal sedentary periods[@wilmotSedentaryTimeAdults2012], and adequate sleep[@cappuccioSleepDurationAllcause2010]. The robust evidence highlighting the health benefits of optimal sleep and daily moderate-to-vigorous physical activity (MVPA) has led to the formation of public guidelines such as the American recommendation of 150 minutes of MVPA per week[@klPhysicalActivityGuidelines2018], and the Danish suggestion of 30 minutes of MVPA per day for adults[@el-zineFysiskAktivitetVoksne] and 60 minutes per day for children[@el-zineFysiskAktivitetBorn]. Furthermore, it's advised that adults get 7-8 hours of sleep[@consensusconferencepanelRecommendedAmountSleep2015], whereas children aged 6-12 should sleep 9-12 hours and teenagers aged 13-18 should aim for 8-10 hours of sleep regularly[@paruthiConsensusStatementAmerican2016]. A growing body of evidence suggesting a link between high sedentary periods and negative health outcomes has led to guidelines advocating for decreasing and interrupting sitting time[@tremblaySedentaryBehaviorResearch2017]. Traditionally, the relationship between time spent on each of these behaviors throughout a 24-hour cycle and health outcomes has been studied separately, neglecting the potential inter-connectedness of these activities[@rosenberger24HourActivityCycle2019].

Previous research has shown that, apart from the many health benefits linked to maintaining sufficient PA levels, it also correlates with improved sleep duration and quality[@kredlowEffectsPhysicalActivity2015]. As expected, there is also evidence suggesting that better sleep may encourage increased PA[@lambiaseTemporalRelationshipsPhysical2013; @mcglincheyPhysicalActivitySleep2014], with a rising number of studies indicating a connection between these two behaviors[@dolezalInterrelationshipSleepExercise2017; @chennaouiSleepExerciseReciprocal2015]. Various studies have observed daily correlations between PA and sleep[@petteegabrielBidirectionalAssociationsAccelerometerdetermined2017; @kishidaIntensiveLongitudinalExamination2016]. However, these findings have shown inconsistencies, largely attributed to the varied measurement methodologies. Traditionally, data on time spent on different physical behaviors has been gathered using self-reported tools such as questionnaires, diaries, or interviews[@dowdSystematicLiteratureReview2018]. In addition to recall and response bias, the challenges of self-reporting include the difficulty of monitoring multiple behaviors simultaneously[@rosenberger24HourActivityCycle2019]. As a result, most published research has generally focused on a single behavior. Some of these limitations can be addressed with 24-hour accelerometer-based protocols, especially those worn on the wrist[@rosenberger24HourActivityCycle2019]. Wrist accelerometers are small, non-invasive, waterproof[@welkReliabilityAccelerometrybasedActivity2004], allowing for continuous, 24-hour wear with minimal disruption to the wearer, and permit uninterrupted activity measurement throughout the day, thereby tracking and analyzing daily changes in PA and sleep behaviors. Furthermore, the latest accelerometers supply raw acceleration data that can be processed using open-source analytical techniques to produce estimates of sleep, sedentary behavior, and PA[@miguelesComparabilityAccelerometerSignal2019]. Simultaneous measurement of physical behaviors, particularly feasible with wrist accelerometry, can offer a better comprehension of the influence of these behaviors on health indicators and their interrelationships. This data could be critical in shaping future health recommendations or interventions.

#### Scope and Relevance

-The need for cost-effective, reliable, and practical alternatives for large-scale studies. - The potential of free-living accelerometers, and why they are a compelling subject of study.

#### Existing Challenges

-   Discuss the challenges with existing methods, such as identifying non-wear time, annotating in-bed periods, and classifying awake periods during in-bed time.
-   Address the lack of exploration of certain sensor locations, like the thigh.

#### Thesis Goals and Objectives

-   Clearly state the aim and objectives of your thesis.
-   Explain how your thesis will address the identified challenges, including improving the manual annotation of in-bed periods, enhancing non-wear detection, and estimating sleep quality metrics.

#### Overview of the Papers

-   Briefly introduce each paper, highlighting the key research question, methods, and findings.

-   Explain how each paper contributes to your thesis goals and objectives.

### Motivation for the Research

#### The Need for Improved Annotation Techniques

-   Importance of accurate annotation in accelerometer data analysis.
-   A brief discussion of the first paper's findings and implications.

#### Improving Non-Wear Detection

-   Explain the implications of undetected non-wear time on data quality.
-   Highlight the findings of your second paper and its relevance.

#### Advancing Sleep Quality Estimation

-   Discuss the impact of sleep quality estimation on understanding human sleep behavior.
-   Briefly describe the conclusions of your third paper.

### Methodological Approaches

-   Give a brief overview of the methods used across all three studies, such as the use of machine learning models, deep learning techniques, manual annotation, and decision tree models.

-   Explain how these methods address the research objectives and the challenges identified earlier.

### Thesis Structure

Provide an outline of the subsequent chapters of your thesis.

# Test Header

Utilizing machine learning for sleep and physical activity identification from accelerometry data is a burgeoning field. This approach offers potential to model complex non-linear relationships unattainable with simple statistical methods such as multiple linear or logistic regression [@fiorillo_automated_2019]. However, supervised machine learning requires large amounts of accurately annotated data to ensure accuracy and generalizability[@van_der_ploeg_modern_2014].

Sleep is considered a vital element for the overall health and development of children[@chaput_systematic_2017; @chaput_systematic_2016; @st-onge_sleep_2016]. Healthy sleep is characterized by sufficient duration, appropriate timing, quality, and absence of disturbances or disorders[@gruber_position_2014]. Despite its importance, the use of advanced machine learning techniques to assess sleep measures from accelerometer data remains underdeveloped[@haghayegh_application_2020].

Accelerometry provides an affordable and minimally invasive method to analyze sleep patterns. Objective measurements are crucial for insights into individual and population-wide circadian rhythms. Polysomnography (PSG), the gold standard for objective sleep assessment, records electroencephalographic (EEG), electromyographic (EMG), and electrooculographic (EOG) activity. However, PSG is costly and burdensome due to technician support requirements, intrusive sensor placements, and overnight monitoring[@vaughn_technical_2008].

Recent studies have tried to use machine learning techniques for PSG-assessed sleep-wake classification with wrist acceleration[@haghayegh_application_2020; @sundararajan_sleep_2021; @hees_novel_2015]. Sundararajan et al.[@sundararajan_sleep_2021] used a random forest machine learning algorithm, achieving an F1 score of 73.9%. However, the high false discovery rate indicates limitations in wrist-worn accelerometers, possibly due to the lack of subject variation and the use of single-night PSG-recordings.

To overcome these limitations, researchers should increase the number of subjects and recording days to capture more variation in movement behavior during sleep. Accelerometry, despite its limitations, is practical for extended recordings outside of the lab [@van_de_water_objective_2011]. The focus should be on developing algorithms for sleep timing rather than sleep staging.

Identifying sleep/wake cycles from accelerometry data requires time in bed annotation, when participants go to bed and wake up. Although this isn't actual sleep time, accelerometry is still widely used in sleep research due to its practical advantages [@hees_novel_2015; @madsen_actigraphy_2013; @schwab_actigraphy_2018; @barouni_ambulatory_2020] This annotation could be based on individual sleep diaries, EEG-based recordings [@younes_staging_2016], or systems for recording tracheal sounds [@dafna_sleep-wake_2015; @montazeri_ghahjaverestan_sleepwakefulness_2020].

This study aims to (1) describe a method for manual annotation of bedtime and wake-up time with raw accelerometry, (2) evaluate the accuracy of manual annotation against a single-channel EEG-based sleep staging system and sleep diary, and (3) assess the inter- and intra-rater reliability of annotations.

------------------------------------------------------------------------

The use of body-worn motion sensors, especially accelerometers, to study human physical activity behavior has gained significant popularity over recent years, offering an efficient and cost-effective method for capturing objective movement data [@dowd_systematic_2018; @loyen_sedentary_2017; @montoye_raw_2018; @migueles_comparability_2019]. These devices can be worn during various activities with some protocols allowing detachment during water-based activities, sleep, or certain sports to prevent injury.

However, such detachment periods, referred to as non-wear time, present researchers with a challenge in the form of missing data. Non-wear time can significantly influence the outcomes derived from the acceleration measurements [@lee_missing_2018]. While some researchers exclude these periods or attempt to impute the missing data using various methods, such strategies can introduce bias, particularly when non-wear times are longer. This issue underscores the importance of accurately classifying and handling non-wear periods for reliable estimates of subjects' physical activity behavior during free-living [@lee_missing_2018].

The classification of non-wear periods can be acquired by having subjects keep individual log diaries, although this method can be cumbersome and potentially error-prone [@ainsworth_recommendations_2012]. In a bid to reduce subject burden and enhance accuracy, researchers have employed rule-based methods and advanced algorithms to classify non-wear time [@hecht_methodology_2009; @ruiz_objectively_2011; @troiano_physical_2008]. Yet, such methods can yield disparate physical activity and sedentary behavior aggregates depending on non-wear settings, age, and obesity level, limiting their utility and the ability to make comparisons across studies [@aadland_comparison_2018; @toftager_accelerometer_2013].

Advancements in accelerometer technology in recent years have enabled researchers to store raw accelerations, enhancing data granularity and potentially improving non-wear period classification [@duncan_wear-time_2018; @rasmussen_short-term_2020; @zhou_classification_2015]. However, even with access to higher quantity and quality data, simple duration-based algorithms carry the risk of falsely misclassifying true non-wear as inactivity, restricting the ability to detect non-wear episodes shorter than the designated interval.

Recently, studies have explored the potential of machine learning, including random forests and deep learning techniques, to classify non-wear using raw accelerometer data [@sundararajan_sleep_2021, @syed_novel_2021]. Machine learning algorithms aim to learn patterns from the training data and approximate the complex model that best describes the relationship between the predictors and the outcome. The balance between model variance and bias is a critical consideration in this process, with the ultimate goal of optimizing the predictive performance of a machine-learned model on unseen data.

Despite the performance of models utilizing complex machine learning algorithms on testing data, their performance on external unseen data remains largely unknown. This gap in knowledge is often due to a lack of out-of-distribution data sources and the desire to incorporate all available data into model training to maximize information capture. Some studies have utilized surface skin temperature in conjunction with raw acceleration for non-wear classification [@duncan_wear-time_2018; @zhou_classification_2015], but the performance and generalizability of adding surface skin temperature with advanced machine learning methods have yet to be explored.

Despite technological advancements, there is still room for improvement in accurately classifying non-wear time in raw accelerometer data. It prompts the question: what heuristic algorithm or machine-learned model will perform best on unseen data for classifying non-wear time? To address this, we created three datasets of raw accelerometer data with correctly labeled wear- and non-wear time, including surface skin temperature measurements. Our study aims to (1) train three decision tree models on accelerometer data from thigh and hip-worn accelerometers for non-wear time classification and evaluate the importance of surface skin temperature and minimizing the number of predictors provided to the model, and (2) assess the performance of machine-learned models and simple heuristic algorithms across datasets of varying age ranges for non-wear time classification.

------------------------------------------------------------------------

A vast body of research highlights the critical role of sleep in maintaining both mental and physical health[@ma_sleep_2017; @meyer_circadian_2022; @k_pavlova_sleep_2019; @difrancesco_sleep_2019]. Consequently, accurate sleep assessment methods are crucial for tracking sleep patterns and improving our understanding of the sleep-health relationship. Furthermore, the ease of use and high acceptability of these methods are essential to facilitate large-scale, longitudinal studies.

The traditional gold standard for objective sleep measurement, laboratory-based polysomnography (PSG), has been found to be impractical in large-scale epidemiological studies due to its high cost, need for professional administration, and susceptibility to rater bias[@van_de_water_objective_2011; @lee_interrater_2022]. As an alternative, diaries have been used due to their cost-effectiveness and simplicity, although they are subject to recall bias and other limitations[@moore_actigraphy_2015]. An innovative approach involves device-based measurement methods. These tools, which estimate sleep duration, are advantageous due to their reduced participant burden and elimination of potential recall biases. A prominent example of such tools is body-worn accelerometers, which offer a practical and affordable means of objectively assessing sleep patterns at home for extended periods. Accelerometers collect continuous, high-resolution data for several weeks without requiring recharging, further minimizing participant burden. Their use in sleep and wake classification began with a wrist movement-based algorithm developed in 1982, and validated using PSG[@webster_activity-based_1982]. This algorithm was refined in 1992[@cole_automatic_1992], leading to the widely adopted Cole-Kripke model. With advancements in the field, a variety of techniques, including heuristic algorithms, machine learning models, regression, and deep learning, are now used to analyze data from hip and wrist-worn accelerometers[@palotti_benchmark_2019; @cole_automatic_1992; @sazonov_activity-based_2004; @sadeh_activity-based_1994; @hees_novel_2015; @sundararajan_sleep_2021].

While wrist and hip-worn devices have benefited from extensive methodological development, thigh-worn accelerometers have not seen the same level of advancement. Existing studies mainly focus on distinguishing sleep from wakefulness, with emphasis on defining 'waking time' and 'bedtime' [@carlson_validity_2021; @inan-eroglu_comparison_2021; @van_der_berg_identifying_2016; @winkler_identifying_2016]. Recent strides in estimating sleep duration using thigh-worn devices have been made, including the introduction of a promising algorithm and its comparison against PSG[@johansson_development_2023]. Despite these advancements, the application of machine learning techniques in this area is still unexplored. Considering the potential of thigh-worn accelerometers for accurate physical behavior assessment[@skotte_detection_2014; @arvidsson_re-examination_2019], there is a significant research gap. Therefore, future studies need to develop techniques similar to those used for wrist and hip-worn accelerometers, with the ultimate goal of establishing a more holistic, accurate, and user-friendly method of sleep and physical activity tracking.

The Zmachine®️ Insight+ (ZM) emerges as a valuable tool within this landscape. Favorably validated against PSG[@kaplan_performance_2014; @wang_evaluation_2015], the ZM provides comparable data without the high costs or the need for professional monitoring typically associated with PSG. Crucially, the ZM facilitates multi-night analysis in free-living conditions due to its ease of use[@pedersen_self-administered_2021], capturing the natural variations in sleep patterns. This makes it advantageous over single-night PSG, particularly as a gold standard data source in machine learning tasks, as it provides multiple nights of measurements without inter-rater bias. Despite these benefits, the ZM, like PSG, still poses a significant participant burden and cost, reinforcing the need for more accessible alternatives like accelerometers.

Our primary objective in this study was to evaluate a range of machine learning and deep learning models, utilizing the raw data collected from a tri-axial thigh-worn accelerometer to estimate in-bed and sleep time. To ensure the reliability and effectiveness of our models, we compared their outputs with an electroencephalography-based (EEG) sleep tracking device, which we, in this current study, considered as the gold standard for measuring sleep. Furthermore, our secondary goal was to assess the developed models' performance in evaluating important sleep quality metrics, including sleep period time (SPT), total sleep time (TST), sleep efficiency (SE), latency until persistent sleep (LPS), and wake after sleep onset (WASO).

\newpage

# References
